name: Release

on:
  push:
    tags:
      - '*.*.*'

jobs:
  release:
    name: Publish release
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Download Erlang/OTP and Rebar
        uses: erlef/setup-beam@v1
        with:
          otp-version: '23.0.x'
          rebar3-version: '3.19.x'
      - name: Compile code
        run: rebar3 compile
      - name: Build escript
        run: rebar3 escriptize
      - name: Run escript
        run: _build/default/bin/stun stun.conversations.im
      - name: Run escript (port number)
        run: _build/default/bin/stun stun.conversations.im 3478
      - name: Run escript (IPv4)
        run: _build/default/bin/stun -4 stun.conversations.im
      - name: Run escript (IPv4, port number)
        run: _build/default/bin/stun -4 stun.conversations.im 3478
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: _build/default/bin/stun
          omitBody: true
